export const countryList = [
  '🇺🇳 United Nations',
  '🇦🇴 Angola',
  '🇧🇫 Burkina Faso',
  '🇧🇮 Burundi',
  '🇧🇯 Benin',
  '🇧🇼 Botswana',
  '🇨🇩 Congo - Kinshasa',
  '🇨🇫 Central African Republic',
  '🇨🇬 Congo - Brazzaville',
  '🇨🇮 Côte d’Ivoire',
  '🇨🇲 Cameroon',
  '🇨🇻 Cape Verde',
  '🇩🇯 Djibouti',
  '🇩🇿 Algeria',
  '🇪🇬 Egypt',
  '🇪🇭 Western Sahara',
  '🇪🇷 Eritrea',
  '🇪🇹 Ethiopia',
  '🇬🇦 Gabon',
  '🇬🇭 Ghana',
  '🇬🇲 Gambia',
  '🇬🇳 Guinea',
  '🇬🇶 Equatorial Guinea',
  '🇬🇼 Guinea-Bissau',
  '🇰🇪 Kenya',
  '🇰🇲 Comoros',
  '🇱🇷 Liberia',
  '🇱🇸 Lesotho',
  '🇱🇾 Libya',
  '🇲🇦 Morocco',
  '🇲🇬 Madagascar',
  '🇲🇱 Mali',
  '🇲🇷 Mauritania',
  '🇲🇺 Mauritius',
  '🇲🇼 Malawi',
  '🇲🇿 Mozambique',
  '🇳🇦 Namibia',
  '🇳🇪 Niger',
  '🇳🇬 Nigeria',
  '🇷🇼 Rwanda',
  '🇸🇨 Seychelles',
  '🇸🇩 Sudan',
  '🇸🇱 Sierra Leone',
  '🇸🇳 Senegal',
  '🇸🇴 Somalia',
  '🇸🇸 South Sudan',
  '🇸🇿 Eswatini',
  '🇹🇩 Chad',
  '🇹🇬 Togo',
  '🇹🇳 Tunisia',
  '🇹🇿 Tanzania',
  '🇺🇬 Uganda',
  '🇿🇦 South Africa',
  '🇿🇲 Zambia',
  '🇿🇼 Zimbabwe',
  '🇦🇬 Antigua & Barbuda',
  '🇦🇮 Anguilla',
  '🇦🇷 Argentina',
  '🇦🇼 Aruba',
  '🇧🇧 Barbados',
  '🇧🇱 St. Barthélemy',
  '🇧🇲 Bermuda',
  '🇧🇴 Bolivia',
  '🇧🇶 Caribbean Netherlands',
  '🇧🇷 Brazil',
  '🇧🇸 Bahamas',
  '🇧🇿 Belize',
  '🇨🇦 Canada',
  '🇨🇱 Chile',
  '🇨🇴 Colombia',
  '🇨🇷 Costa Rica',
  '🇨🇺 Cuba',
  '🇨🇼 Curaçao',
  '🇩🇲 Dominica',
  '🇩🇴 Dominican Republic',
  '🇪🇨 Ecuador',
  '🇫🇰 Falkland Islands',
  '🇬🇩 Grenada',
  '🇬🇫 French Guiana',
  '🇬🇵 Guadeloupe',
  '🇬🇹 Guatemala',
  '🇬🇾 Guyana',
  '🇭🇳 Honduras',
  '🇭🇹 Haiti',
  '🇯🇲 Jamaica',
  '🇰🇳 St. Kitts & Nevis',
  '🇰🇾 Cayman Islands',
  '🇱🇨 St. Lucia',
  '🇲🇫 St. Martin',
  '🇲🇶 Martinique',
  '🇲🇸 Montserrat',
  '🇲🇽 Mexico',
  '🇳🇮 Nicaragua',
  '🇵🇦 Panama',
  '🇵🇪 Peru',
  '🇵🇲 St. Pierre & Miquelon',
  '🇵🇷 Puerto Rico',
  '🇵🇾 Paraguay',
  '🇸🇷 Suriname',
  '🇸🇻 El Salvador',
  '🇸🇽 Sint Maarten',
  '🇹🇨 Turks & Caicos Islands',
  '🇹🇹 Trinidad & Tobago',
  '🇺🇸 United States',
  '🇺🇾 Uruguay',
  '🇻🇪 Venezuela',
  '🇻🇬 British Virgin Islands',
  '🇻🇮 U.S. Virgin Islands',
  '🇦🇪 United Arab Emirates',
  '🇦🇫 Afghanistan',
  '🇦🇿 Azerbaijan',
  '🇧🇩 Bangladesh',
  '🇧🇭 Bahrain',
  '🇧🇳 Brunei',
  '🇧🇹 Bhutan',
  '🇨🇳 China',
  '🇭🇰 Hong Kong SAR China',
  '🇮🇩 Indonesia',
  '🇮🇱 Israel',
  '🇮🇳 India',
  '🇮🇶 Iraq',
  '🇮🇷 Iran',
  '🇯🇴 Jordan',
  '🇯🇵 Japan',
  '🇰🇬 Kyrgyzstan',
  '🇰🇭 Cambodia',
  '🇰🇵 North Korea',
  '🇰🇷 South Korea',
  '🇰🇼 Kuwait',
  '🇰🇿 Kazakhstan',
  '🇱🇦 Laos',
  '🇱🇧 Lebanon',
  '🇱🇰 Sri Lanka',
  '🇲🇲 Myanmar (Burma)',
  '🇲🇳 Mongolia',
  '🇲🇴 Macao Sar China',
  '🇲🇻 Maldives',
  '🇲🇾 Malaysia',
  '🇳🇵 Nepal',
  '🇴🇲 Oman',
  '🇵🇭 Philippines',
  '🇵🇰 Pakistan',
  '🇵🇸 Palestinian Territories',
  '🇶🇦 Qatar',
  '🇷🇺 Russia',
  '🇸🇦 Saudi Arabia',
  '🇸🇬 Singapore',
  '🇸🇾 Syria',
  '🇹🇭 Thailand',
  '🇹🇯 Tajikistan',
  '🇹🇱 Timor-Leste',
  '🇹🇲 Turkmenistan',
  '🇹🇷 Türkiye',
  '🇹🇼 Taiwan',
  '🇺🇿 Uzbekistan',
  '🇻🇳 Vietnam',
  '🇾🇪 Yemen',
  '🇦🇩 Andorra',
  '🇦🇱 Albania',
  '🇦🇲 Armenia',
  '🇦🇹 Austria',
  '🇧🇦 Bosnia & Herzegovina',
  '🇧🇪 Belgium',
  '🇧🇬 Bulgaria',
  '🇧🇾 Belarus',
  '🇨🇭 Switzerland',
  '🇨🇾 Cyprus',
  '🇨🇿 Czechia',
  '🇩🇪 Germany',
  '🇩🇰 Denmark',
  '🇪🇦 Ceuta & Melilla',
  '🇪🇪 Estonia',
  '🇪🇸 Spain',
  '🇪🇺 European Union',
  '🇫🇮 Finland',
  '🇫🇷 France',
  '🇬🇧 United Kingdom',
  '🇬🇪 Georgia',
  '🇬🇬 Guernsey',
  '🇬🇮 Gibraltar',
  '🇬🇷 Greece',
  '🇭🇷 Croatia',
  '🇭🇺 Hungary',
  '🇮🇪 Ireland',
  '🇮🇲 Isle of Man',
  '🇮🇸 Iceland',
  '🇮🇹 Italy',
  '🇯🇪 Jersey',
  '🇱🇮 Liechtenstein',
  '🇱🇹 Lithuania',
  '🇱🇺 Luxembourg',
  '🇱🇻 Latvia',
  '🇲🇨 Monaco',
  '🇲🇩 Moldova',
  '🇲🇪 Montenegro',
  '🇲🇰 North Macedonia',
  '🇲🇹 Malta',
  '🇳🇱 Netherlands',
  '🇳🇴 Norway',
  '🇵🇱 Poland',
  '🇵🇹 Portugal',
  '🇷🇴 Romania',
  '🇷🇸 Serbia',
  '🇷🇺 Russia',
  '🇸🇪 Sweden',
  '🇸🇮 Slovenia',
  '🇸🇰 Slovakia',
  '🇸🇲 San Marino',
  '🇺🇦 Ukraine',
  '🇻🇦 Vatican City',
  '🇽🇰 Kosovo',
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
  '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland',
  '🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales',
  '🇦🇨 Ascension Island',
  '🇦🇶 Antarctica',
  '🇦🇸 American Samoa',
  '🇦🇺 Australia',
  '🇦🇽 Åland Islands',
  '🇧🇻 Bouvet Island',
  '🇨🇨 Cocos (Keeling) Islands',
  '🇨🇰 Cook Islands',
  '🇨🇵 Clipperton Island',
  '🇨🇽 Christmas Island',
  '🇩🇬 Diego Garcia',
  '🇫🇯 Fiji',
  '🇫🇲 Micronesia',
  '🇬🇱 Greenland',
  '🇬🇸 South Georgia & South Sandwich Islands',
  '🇬🇺 Guam',
  '🇭🇲 Heard & McDonald Islands',
  '🇮🇨 Canary Islands',
  '🇮🇴 British Indian Ocean Territory',
  '🇰🇮 Kiribati',
  '🇲🇭 Marshall Islands',
  '🇲🇵 Northern Mariana Islands',
  '🇳🇨 New Caledonia',
  '🇳🇫 Norfolk Island',
  '🇳🇷 Nauru',
  '🇳🇺 Niue',
  '🇳🇿 New Zealand',
  '🇵🇫 French Polynesia',
  '🇵🇬 Papua New Guinea',
  '🇵🇳 Pitcairn Islands',
  '🇵🇼 Palau',
  '🇷🇪 Réunion',
  '🇸🇧 Solomon Islands',
  '🇸🇭 St. Helena',
  '🇸🇯 Svalbard & Jan Mayen',
  '🇸🇹 São Tomé & Príncipe',
  '🇹🇦 Tristan Da Cunha',
  '🇹🇫 French Southern Territories',
  '🇹🇰 Tokelau',
  '🇹🇴 Tonga',
  '🇹🇻 Tuvalu',
  '🇺🇲 U.S. Outlying Islands',
  '🇻🇨 St. Vincent & Grenadines',
  '🇻🇺 Vanuatu',
  '🇼🇫 Wallis & Futuna',
  '🇼🇸 Samoa',
  '🇾🇹 Mayotte',
];
